### ISSUE TITLE
crash on main menu while trying to change resource pack

### ISSUE THREAD

**Issue by Yonk316** [Chaos-Awakens-Mod-Team/ChaosAwakens#31] opened 2021-10-06 12:18 UTC
[crash-2021-10-06_08.16.05-client.txt](https://github.com/ChaosAwakens/ChaosAwakens/files/7293606/crash-2021-10-06_08.16.05-client.txt)

**Comment by invalid2** [comment] 2021-10-09 15:26
I will be looking into it, should be fixed soon

**Comment by invalid2** [comment] 2021-10-12 15:14
I was unable to reproduce your crash, so I did changes that should fix it. If the crash continues to happen feel free to re-open this issue

**Closed as completed** 2021-10-12 15:14 UTC
