### ISSUE TITLE
Gekolib3 not compatible

### ISSUE THREAD

**Issue by biscuit-the-wolf** [Chaos-Awakens-Mod-Team/ChaosAwakens#152] opened 2024-11-23 03:50 UTC
The Geckolib3 mods latest verion is not compatible with Chaosawakens and the version that is comptible with it is not compatible with the ars_nouveau mod and the mowziesmods mod. they need the newest version of gecko while choas needs an older version.
![image_2024-11-22_214935175](https://github.com/user-attachments/assets/8a71ee3b-0ff6-43cb-8417-23d528d44275)

**Comment by uncertainluei** [comment] 2024-11-23 15:23
Duplicate of #128

**Closed as not planned by uncertainluei** 2024-11-23 15:23 UTC
